@startuml MetalK_MER
    top to bottom direction
    skinparam linestyle orto

    entity emp as "Empresa"{
        dirección
        nombre
        logo
        slogan
        teléfono
        redes
    }

    entity pro as "Producto"{
        precio
        tiempo
        estado
        categoría
    }

    entity sol as "Solicitud"{
        fecha
        estado
        dirección
        plano
        visitaTécnica
    }

    entity car as "Características"{
        nombre
        descripción
        agrupación
    }

    entity int as "Interesado"{
        nombre
        teléfono
    }

    pro }|-right-|{ car : tiene
    int ||-down-|{ sol : realiza
    sol ||--|| pro : pertenece
    emp ||-right-|{ sol: dirigida
@enduml