 @startuml MetalK_ExternalActors
    top to bottom direction
    skinparam linetype ortho

    actor Interesado as I
    actor Admin as A
    node "Metal K Web Center" as MK
    node WhatsApp as W

    I <-down-> MK
    A <-left-> MK
    W <-right-> MK
 @enduml
