@startuml MetalK_MER
    top to bottom direction
    skinparam linestyle orto

    entity emp as "Empresa"{
        direccion
        nombre
        logo
        slogan
        telefono
        redes
    }

    entity pro as "Producto"{
        precio
        tiempo
        estado
        categoria
    }

    entity sol as "Solicitud"{
        fecha
        estado
        direccion
        plano
        visitaTecnica
    }

    entity cot as "Cotización"{
        items
        total
    }
    
    entity car as "Caracteristicas"{
        nombre
        descripcion
        agrupacion
    }

    entity cli as "Interesado"{
        nombre
        telefono
    }

    pro }|-right-|{ car
    cli ||-right-|{ sol
    sol ||--|| pro
    sol ||-right-|| cot


@enduml