@startuml MetalK_MER
    top to bottom direction
    skinparam linestyle orto

    entity emp as "Empresa"{
        direccion
        nombre
        logo
        slogan
        telefono
        redes
    }

    entity pro as "Producto"{
        precio
        tiempo
        categoria
    }

    entity sol as "Solicitud"{
        fecha
        aceptado
        plano
        direccion
    }

    entity cot as "Cotización"{
        items
        total
    }
    
    entity car as "Caracteristicas"{
        nombre
        descripcion
    }

    entity cli as "Cliente"{
        nombre
        telefono
    }

    emp ||-right-o{ pro
    pro }|-right-|{ car
    cli ||-right-|{ sol
    sol ||--|| pro
    sol ||-right-|| cot


@enduml