@startuml MetalK_Packages
    skinparam nodesep 4
    skinparam linestyle orto

    <style>
    database {
        
    }
    package{

    }
    </style>

    database BaseDeDatos as bd{          
    }
    package Solicitud as sol{
        package Personalizacion as per{}
        package Prospectos as pros{}
    }
    package Mensajeria as wasa{}
    package Portafolio as por{}
    package Cotizacion as cot{
        package VisitaTecnica as vt{}
        package Diseño as dis{}
    }
    package Almacenamiento as alm{}
    package Cartera as car{
        package Contratacion as con{}
        package CompraMaterial as cm{}
        package CuentaDeCobro as cdc{}
    }
    package AccesoDatos as ad{}
    package Cronograma as cro{}
    package Produccion as pro{}
    package Clientes as cli{}
    

    sol -(0- wasa 
    sol -(0-cro 
    sol -0)- cot 
    por -(0- pro
    pro -(0- alm
    pro -(0- wasa
    car -0)- pro
    alm -(0- car
    ad -(0- bd  
    pro -0)- cro
    cot -0)- car
    cli -0)- sol
    cli -0)- car
    ad -0)- car
    ad -0)- cli
    
@enduml