@startuml MetalK_Packages
    skinparam nodesep 4
    skinparam linestyle orto

    <style>
    database {
        
    }
    package{

    }
    </style>

    database BaseDeDatos as bd{          
    }
    package Solicitud as sol{}
    package Mensajeria as wasa{}
    package VisitaTecnica as vt{}
    package Personalizacion as per{}
    package Diseño as dis{}
    package Portafolio as por{}
    package Cotizacion as cot{}
    package Almacenamiento as alm{}
    package CuentaDeCobro as cdc{}
    package Manofactura as man{}
    package Contabilidad as con{}
    package AccesoDatos as ad{}
    package Cronograma as cro{}
    package Entrega as ent{}
    package CompraMaterial as cm{}
    package Contratacion as cont{}

    sol -(0- wasa 
    sol -(0-cro
    sol -(0- per
    dis -(0- per
    dis -(0- vt
    cro -0)- vt   
    cot -(0- dis
    por -(0- ent
    man -(0- alm
    ent -(0- wasa
    man -0)- ent
    con -(0- cdc
    cm -0)- con
    con -0)- ent
    alm -(0- con
    cm -(0- alm
    ad -(0- bd  
    cot -0)- con
    man -0)- cro
    con -0)- cont
    cont -(0- man
    
@enduml