@startuml MetalK_PackagesWInterfaces
    skinparam nodesep 4
    skinparam linestyle orto

    <style>
    database {
        
    }
    package{

    }
    </style>

    database BaseDeDatos as bd{          
    }
    package Solicitud as sol{
        package Personalizacion as per{}
        package Prospectos as pros{}
    }
    
    package Mensajeria as wasa{}

    package Portafolio as por{}

    package Cotizacion as cot{
        package VisitaTecnica as vt{}
        package Diseño as dis{}
    }

    package Almacenamiento as alm{}

    package Cartera as car{
        package Contratacion as con{}
        package CompraMaterial as cm{}
        package CuentaDeCobro as cdc{}
    }

    package AccesoDatos as ad{}

    package Cronograma as cro{}

    package Produccion as pro{}

    package Clientes as cli{}
    
    interface "Solicitud" as solI{
        obtenerPreferencias()
    }

    interface "Whatsapp" as wasaI{
        enviarMensajeACliente()
        enviarMensajeAAdministrador()
    }

    interface "Cronograma" as croI{
        programarVisitaTecnica()
        inicioDeObra()
        finalizacionDeObra()
        programarEntrega()
    }

    interface "Cartera" as carI{
        solicitarCompra()
        solicitarManoDeObra()
    }

    interface "Almacenamiento" as almI{
        gastarMaterial()
    }

    interface "Cotizacion" as cotI{
        obtenerItems()
    }

    interface "Cliente" as cliI{
        crearCliente()
    }

    interface "Producto" as proI{
        productoTerminado()
    }

    
    interface "AccesoDatos" as adI{
        consultar()
    }
    sol --> wasaI
    cro --> wasaI
    wasaI <-- wasa
    sol --> croI
    pro --> croI
    croI <-- cro
    cot --> solI
    solI <-- sol
    pro --> carI
    alm --> carI
    carI <-- car
    pro --> almI
    almI <-- alm
    por --> proI
    proI --> pro
    car -- cotI
    cotI --> cot
    sol -- cliI
    cliI --> cli
    cli -- adI
    car -- adI
    adI --> ad
    ad -(0- bd  
    
@enduml