@startuml MetalK_UseCase_Portfolio
    left to right direction

    actor Admnistrador as a
    actor Interesado as i


    rectangle Portafolio{
        usecase "RF001-Iniciar sesión" as RF001
        usecase "RF014-Visualizar productos" as RF014
        usecase "RF015-Filtrar productos por categoría" as RF015a
        usecase "RF015-Filtrar productos por categoría" as RF015i
        usecase "RF016-Filtrar productos por tags" as RF016
        usecase "RF017-Organizar aleatoriamente los productos" as RF017
        usecase "RF018-Organizar cronológicamente los productos" as RF018
        usecase "RF019-Visualizar principales \n características del producto" as RF019
    }   

    a -down-> RF018
    a -down-> RF015a

    i -down-> RF017
    i -down-> RF015i
    i -down-> RF019

    RF018 .down.> RF014:<include>
    RF017 .down.> RF014:<include>
    RF015i <.down. RF016:<extends>
    RF015a <.down. RF016:<extends>
    RF015i .left.> RF017:<include>
    RF015a .right.> RF018:<include>

    RF018 .down.> RF001:<include>
@enduml