@startuml MetalK_DataModel
    skinparam linestyle orto
    entity sol as "Solicitud"{
        nombreInteresado
        telefonoInteresado
        direccion
        estado
        plano
        visitaTecnica
    }

    entity pro as "Producto"{
        estado
        precio
        categoria
    }
    entity cat as "Categoria" {   
        nombre
        descripcion
    }

    entity gt as "GrupoTag" {   
        nombre
        descripcion
    }

    entity tag as "Tag" {   
        nombre
        descripcion
    }

    entity emp as "Empresa"{
        direccion
        nombre
        logo
        slogan
        telefono
    }


    tag }|-left-{ pro
    pro ||-left-|| sol
    pro }-down-|| cat
    tag }|-right-|| gt
    cat }|-right-|{ tag
    
    note top of tag: Esta es la representacion de \n "Caracteristicas" en el sistema
    note left of cat: La Categoria del Producto \ncondiciona los Tag que puede tener

    
@enduml
