@startuml MetalK_DataModel
    skinparam linestyle orto

    entity soli as "Solicitudes"{
        # soli_id: int
        soli_date: date
        soli_plane: varchar
        soli_technicalVisit: boolean
        soli_address: varchar
        ~ clin_id: int
    }

    entity clin as "Clients"{
        # clin_id: int
        clin_name: varchar
        clin_cellphone: varchar
    }
    
    entity admi as "Admins"{
        # admi_id: int
        admi_name: varchar
        admi_cellphone: varchar
        admi_password: varchar
    }

    entity prod as "Products"{
        # prod_id: int
        prod_price: double
        prod_time: int
        ~ cate_id: int
    }

    
    entity prpi as "ProductPictures"{
        #prpi_id: int
        prpi_route: varchar
        ~ prod_id: int
    }

    entity prta as "Product_Tags"{
        # prta_id:int
        ~ prod_id: int
        ~ tag_id: int
    }

    entity cate as "Categories" {   
        # cate_id: int
        cate_name: varchar
        cate_description: text
        cate_icon: varchar
    }

    
    entity tagg as "TagGroups" {   
        # tagg_id: int
        tagg_title: varchar
        tagg_description: text
        tagg_icon: varchar
    }

    entity tbca as "TagsByCategory" {   
        # tbca_id: int
        ~ cate_id: int
        ~ tag_id: int
    }

    entity tags as "Tags" {   
        # tag_id:int
        tag_name: varchar
        tag_description: text
        ~ tagg_id: int
    }

    entity ente as "Enterprice"{
        # ente_id: int
        ente_name: varchar
        ente_slogan: varchar
        ente_description: varchar
        ente_logo: file
        ente_address: date
    }


    prod ||-up-|| soli
    prod }--|| cate
    prod ||-left-|{ prpi
    tags }|-down-|| tagg
    cate ||-right-|{ tbca
    tbca }|-right-|| tags
    prod ||-right-|{ prta
    tags ||-left-|{ prta
    clin ||--|{ soli
    
@enduml
