@startuml MetalK_DataModel
    skinparam linestyle orto
    entity sol as "Solicitud"{
        dirección
        estado
        plano
        visitaTécnica
    }

    entity pro as "Producto"{
        estado
        precio
        categoría
    }

    entity cli as "Clients"{
        nombre
        teléfono
    }

    entity cat as "Categoria" {   
        nombre
        descripción
    }

    entity gt as "GrupoTag" {   
        nombre
        descripcion
    }

    entity tag as "Tag" {   
        nombre
        descripción
    }

    entity emp as "Empresa"{
        dirección
        nombre
        logo
        slogan
        teléfono
    }


    tag }|-left-{ pro
    pro ||-left-|| sol
    pro }-down-|| cat
    tag }|-down-|| gt
    cat }|-right-|{ gt
    cli ||--|{ sol
    
    note top of tag: Esta es la representación de \n "Características" en el sistema.
    note left of cat: La Categoría condiciona los Tag\nque puede tener el Producto\npor medio del GrupoTag.

    
@enduml
